import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { fetchPostalLookup } from "../api/postalLookup";

const initialState = {
  loading: false,
  errorMessage: "",
  postalLookup: [],
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const getPostalLookup = createAsyncThunk(
  "postal/getPostalLookup",
  async (code, thunkAPI) => {
    console.log(code);
    try {
      const response = await fetchPostalLookup(code);
      return response.data;
    } catch (error) {
      return thunkAPI.rejectiWithValue(error);
    }
  }
);

export const postalSlice = createSlice({
  name: "postal",
  initialState,

  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: {
    [getPostalLookup.pending]: (state) => {
      state.generalError = false;
      state.errorMessage = "";
      state.loading = true;
    },
    [getPostalLookup.rejected]: (state, action) => {
      state.loading = false;
      state.errorMessage = action.payload;
    },
    [getPostalLookup.fulfilled]: (state, { payload }) => {
      state.loading = false;
      state.postalLookup = payload;
    },
  },
});

export default postalSlice.reducer;
