import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { fetchCountries, fetchUniversities } from "../api/universities";

const initialState = {
  loading: false,
  errorMessage: "",
  universities: [],
  countries: [],
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const getCountries = createAsyncThunk(
  "universities/getCountries",
  async (thunkAPI) => {
    try {
      const response = await fetchCountries();
      return response.data;
    } catch (error) {
      return thunkAPI.rejectiWithValue(error);
    }
  }
);

export const getUniversities = createAsyncThunk(
  "universities/getUniversities",
  async (country, thunkAPI) => {
    try {
      const response = await fetchUniversities(country);
      return response.data;
    } catch (error) {
      return thunkAPI.rejectiWithValue(error);
    }
  }
);

export const universitiesSlice = createSlice({
  name: "universities",
  initialState,

  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: {
    [getCountries.pending]: (state) => {
      state.generalError = false;
      state.errorMessage = "";
      state.loading = true;
    },
    [getCountries.rejected]: (state, action) => {
      state.loading = false;
      state.errorMessage = action.payload;
    },
    [getCountries.fulfilled]: (state, { payload }) => {
      state.loading = false;
      state.countries = payload;
    },
    [getUniversities.pending]: (state) => {
      state.generalError = false;
      state.errorMessage = "";
      state.loading = true;
    },
    [getUniversities.rejected]: (state, action) => {
      state.loading = false;
      state.errorMessage = action.payload;
    },
    [getUniversities.fulfilled]: (state, { payload }) => {
      state.loading = false;
      state.universities = payload;
    },
  },
});

export default universitiesSlice.reducer;
